#!/usr/bin/env bash
set -euo pipefail

export VLLM_ATTENTION_BACKEND=${VLLM_ATTENTION_BACKEND:-XFORMERS}
export ROLLOUT_NAME=${ROLLOUT_NAME:-vllm}
export ROLLOUT_TP_SIZE=${ROLLOUT_TP_SIZE:-1}
export ROLLOUT_N=${ROLLOUT_N:-8}
export USE_REMOVE_PADDING=${USE_REMOVE_PADDING:-False}
export ATTN_IMPLEMENTATION=${ATTN_IMPLEMENTATION:-sdpa}

export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-4}
export VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-64}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-4}
export PPO_MICRO_BATCH_SIZE=${PPO_MICRO_BATCH_SIZE:-1}
export LOG_PROB_MICRO_BATCH_SIZE=${LOG_PROB_MICRO_BATCH_SIZE:-1}
export REF_LOG_PROB_MICRO_BATCH_SIZE=${REF_LOG_PROB_MICRO_BATCH_SIZE:-1}

export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-256}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-192}
export MAX_TOKEN_LEN_PER_GPU=${MAX_TOKEN_LEN_PER_GPU:-4096}
export GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.30}

export TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
export SAVE_FREQ=${SAVE_FREQ:-20}
export TEST_FREQ=${TEST_FREQ:-20}
export VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN:-False}
export LOGGER=${LOGGER:-['console']}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-qwen2_5_1_5b_game24_grpo_vllm_autodl}

bash scripts/train_game24_grpo.sh "$@"
